# Generated by Django 6.1 on 2026-08-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_id', models.CharField(max_length=50)),
                ('consumer_name', models.CharField(max_length=100)),
                ('meter_number', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=100)),
                ('avg_consumption', models.FloatField()),
                ('peak_consumption', models.FloatField()),
                ('prediction_result', models.CharField(max_length=20)),
                ('theft_probability', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
